/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "filesystem.h"

bool_t
xdr_stream (XDR *xdrs, stream *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_filename (XDR *xdrs, filename *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 255))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_read_request (XDR *xdrs, read_request *objp)
{
	register int32_t *buf;

	 if (!xdr_filename (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ammount))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_read_response (XDR *xdrs, read_response *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->ammount))
		 return FALSE;
	 if (!xdr_stream (xdrs, &objp->buffer))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_write_request (XDR *xdrs, write_request *objp)
{
	register int32_t *buf;

	 if (!xdr_filename (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_stream (xdrs, &objp->buffer))
		 return FALSE;
	return TRUE;
}
