/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "timeout.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
some_function_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, some_function, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
some_function_to_22_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, some_function_to_22, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
some_function_to_26_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, some_function_to_26, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}
