/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TIMEOUT_H_RPCGEN
#define _TIMEOUT_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


#define TO_PROG 555553511
#define TO_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define some_function 1
extern  enum clnt_stat some_function_1(int *, CLIENT *);
extern  bool_t some_function_1_svc(int *, struct svc_req *);
extern int to_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define some_function 1
extern  enum clnt_stat some_function_1();
extern  bool_t some_function_1_svc();
extern int to_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TIMEOUT_H_RPCGEN */
